// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuXUc1pBOkz_z1j6GtnfsdUqEBgo8XvDQ',
    appId: '1:77718597188:web:83f1f58dec969295451611',
    messagingSenderId: '77718597188',
    projectId: 'chat-bot-app-41fc1',
    authDomain: 'chat-bot-app-41fc1.firebaseapp.com',
    storageBucket: 'chat-bot-app-41fc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjDBf3xxPJcSPRAq8UKthuhKu0zI09VwM',
    appId: '1:77718597188:android:b55394ff9b329876451611',
    messagingSenderId: '77718597188',
    projectId: 'chat-bot-app-41fc1',
    storageBucket: 'chat-bot-app-41fc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAET3Ah8CVM2PeFOoLYaD7xj6a_RdLSEbI',
    appId: '1:77718597188:ios:bacda40a4ef82758451611',
    messagingSenderId: '77718597188',
    projectId: 'chat-bot-app-41fc1',
    storageBucket: 'chat-bot-app-41fc1.appspot.com',
    iosBundleId: 'com.example.chatGptClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAET3Ah8CVM2PeFOoLYaD7xj6a_RdLSEbI',
    appId: '1:77718597188:ios:0ea8ef21722487fd451611',
    messagingSenderId: '77718597188',
    projectId: 'chat-bot-app-41fc1',
    storageBucket: 'chat-bot-app-41fc1.appspot.com',
    iosBundleId: 'com.example.chatGptClone.RunnerTests',
  );
}
